import type { Metadata } from "next";
import { Geist, Poppins } from "next/font/google";
import "@/styles/global.css";
import Navbar from "@/components/ui/Navbar/Navbar";
import BackgroundImage from "@/components/layout/BackgroundImage";

const geist = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geist.variable} ${poppins.variable} relative antialiased`}
      >
        <BackgroundImage imageUrl="/wallpaper.jpg" />
        <div className="padding-page flex h-screen flex-col justify-around">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
